name: 🍏 iOS Builds
on:
  workflow_call:

jobs:
  ios:
    runs-on: "macos-latest"
    name: iOS Build ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Build ${{ matrix.arch }}
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch }}
          platform: ios

      - name: Upload ${{ matrix.arch }}
        uses: ./.github/actions/upload
