name: 📊 Static Checks
on:
  workflow_call:

jobs:
  static-checks:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Add execute permission to clang-format.sh
        run: chmod +x ./scripts/clang-format.sh

      - name: Clang Format
        shell: sh
        run: ./scripts/clang-format.sh
